dataset_path: few_data/
train_dataset: miniimagenet
train_dataset_args: {split: train, augment: aug1, batch_size: 128}
val_dataset: miniimagenet
val_dataset_args: {split: train_phase_val, batch_size: 128}
test_dataset: miniimagenet
test_dataset_args: {split: test, batch_size: 2}
eval_fs_epoch: 5

model: classifier
model_args:
    encoder: resnet12
    encoder_args: {}
    classifier: linear-classifier 
    classifier_args: {n_classes: 64}

max_epoch: 100
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4, milestones: [90]}

save_epoch: 5
